# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-toolkits/kf5-kwidgetsaddons/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kwidgetsaddons
CATEGORIES=	x11-toolkits kde # kde-framework

COMMENT=	KF5 addons to QtWidgets

USE_QT5=	core gui linguisttools uitools widgets
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
