# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kunitconversion/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kunitconversion
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 library for unit conversion

USE_QT5=	core network xml
USE_KDE5=	ecm i18n kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
