# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-toolkits/kf5-kjobwidgets/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kjobwidgets
CATEGORIES=	x11-toolkits kde # kde-framework

COMMENT=	KF5 widgets for tracking KJob instance

USE_QT5=	core dbus gui linguisttools widgets x11extras
USE_KDE5=	coreaddons ecm kdeprefix service widgetsaddons

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
