# Created by: Nicola Vitale <nivit@FreeBSD.org>
# $FreeBSD: head/textproc/py-pygments/Makefile 406304 2016-01-17 12:03:37Z rakuco $

PORTNAME=	pygments
PORTVERSION=	2.0.2
PORTREVISION=	1
CATEGORIES=	textproc python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Pygments-${PORTVERSION}

MAINTAINER=	nivit@FreeBSD.org
COMMENT=	Syntax highlighter written in Python

LICENSE=	BSD2CLAUSE

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
