# Created by: Naoki Tsurutani
# $FreeBSD: head/www/linux-f10-flashplugin11/Makefile 361777 2014-07-14 12:44:27Z eadler $

PKGNAMEPREFIX=	linux-f10-
USES=		linux:f10
MASTERDIR=	${.CURDIR}/../linux-c6-flashplugin11
ALSA_USE_OFF=	LINUX=openssl

.include "${MASTERDIR}/Makefile"
