# $FreeBSD$

PORTNAME=	calligra-l10n
PORTVERSION=	2.8.7
CATEGORIES=	editors kde spanish

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Basque messages and documentation for Calligra

CALLIGRA_L10N=	eu

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
