# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11/plasma5-plasma/Makefile 10851 2015-07-06 19:33:03Z tcberner $

PORTNAME=	plasma
PORTVERSION=	${KDE_PLASMA_VERSION}
CATEGORIES=     x11 kde # kde-plasma
PKGNAMEPREFIX?= plasma5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE5 plasma meta port

LICENSE=	LGPL20

USE_KDE5=	${_USE_KDE5_PLASMA_ALL}

USES=		metaport

.include <bsd.port.mk>
