# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/sysutils/plasma5-systemsettings/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	systemsettings
CATEGORIES=	sysutils kde # kde-plasma

COMMENT=	Plasma5 system settings

USE_QT5=	core dbus linguisttools
USE_KDE5=	ecm kcmutils kdeprefix khtml

OPTIONS_DEFINE=	DOCS NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>

