# $FreeBSD$

PORTNAME=	kipi-plugin-${KIPI_PLUGIN}
PORTVERSION=	${DIGIKAM_VER}
CATEGORIES=	graphics kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	${${KIPI_PLUGIN}_DESC}

IGNORE=		builds, but files are not accessible on the media server

KIPI_PLUGIN=	dlnaexport
.include "${.CURDIR}/../digikam/Makefile.common"
.include <bsd.port.mk>
