# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-themes/kf5-kiconthemes/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kiconthemes
CATEGORIES=	x11-themes kde # kde-framework

COMMENT=	KF5 library for handling icons in applications

USE_QT5=	concurrent core script svg widgets
USE_KDE5=	configwidgets ecm i18n itemviews kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
