# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kpeople/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kpeople
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 library providing access to contacts

USE_QT5=	core gui qml sql widgets
USE_KDE5=	coreaddons ecm itemviews kdeprefix service widgetsaddons

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
