# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kcrash/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kcrash
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 library to handle crash analysis and bug report from apps

USE_QT5=	core gui widgets x11extras
USE_KDE5=	coreaddons ecm kdeprefix windowsystem

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
