# Created by: Stas Timoklhin <devel@stasyan.com>
# $FreeBSD: head/security/linux-f10-libgpg-error/Makefile 362024 2014-07-16 03:18:26Z adamw $

PORTNAME=	libgpg-error
PORTVERSION=	1.6
PORTREVISION=	1
CATEGORIES=	security linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Common error values for all GnuPG components

RPMVERSION=	2
USES=		linux:f10
USE_LDCONFIG=	yes
USE_LINUX_RPM=	yes

DESCR=		${.CURDIR}/../libgpg-error/pkg-descr

.include <bsd.port.mk>
