# $FreeBSD$

PORTNAME=	kipi-plugin-${KIPI_PLUGIN}
PORTVERSION=	${DIGIKAM_VER}
CATEGORIES=	graphics kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	${${KIPI_PLUGIN}_DESC}

USES=		bison:build

KIPI_PLUGIN=	panorama
.include "${.CURDIR}/../digikam/Makefile.common"
.include <bsd.port.mk>
