# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-wm/plasma5-kdecoration/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	kdecoration
CATEGORIES=	x11-wm kde # kde-plasma

COMMENT=	Plasma5 library to create window decorations

USE_QT5=	core gui
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>

