# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-ki18n/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	ki18n
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 advanced internationalization framework

USE_QT5=	concurrent core script
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
