# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/textproc/kf5-kcodecs/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kcodecs
CATEGORIES=	textproc kde # kde-framework

COMMENT=	KF5 library for string manipulation

USE_QT5=	core linguisttools
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
