# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/net/kf5-kxmlrpcclient/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kxmlrpcclient
CATEGORIES=	net kde # kde-framework

COMMENT=	KF5 interaction with XMLRPC services

USE_QT5=	core
USE_KDE5=	ecm doctools kdeprefix kio

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
