# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11/kf5-kwindowsystem/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kwindowsystem
CATEGORIES=	x11 kde # kde-framework

COMMENT=	KF5 library for access to the windowing system

USE_QT5=	core gui linguisttools widgets x11extras
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
