# $FreeBSD: branches/plasma5/KDE/misc/kdeedu-data/Makefile 10672 2015-04-25 19:17:13Z tcberner $

PORTNAME=	kdeedu-data
PORTVERSION=	${KDE_APPLICATIONS_VERSION}
CATEGORIES=	misc kde
MASTER_SITES=	KDE/${KDE_APPLICATIONS_BRANCH}/applications/${KDE_APPLICATIONS_VERSION}/src
DIST_SUBDIR=	KDE/${PORTVERSION}

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE edu data files

USE_KDE5=	ecm
USES=		cmake:outsource tar:xz

.include <bsd.port.mk>
