# Created by: bsam
# $FreeBSD: head/textproc/linux-f10-aspell/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	aspell
PORTVERSION=	0.60.6
PORTREVISION=	2
CATEGORIES=	textproc linux

MAINTAINER=	emulation@FreeBSD.org
COMMENT=	Spelling checker with better logic than ispell (Linux Fedora 10)

LICENSE=	LGPL21+

USES=		linux:f10
USE_LINUX_RPM=	yes

RPMVERSION=	3.fc10
USE_LDCONFIG=	yes

DESCR=		${.CURDIR}/../${PORTNAME}/pkg-descr

.include <bsd.port.mk>
