# Created by: itetcu@
# $FreeBSD: head/dns/linux-f10-libasyncns/Makefile 340722 2014-01-22 17:00:46Z mat $

PORTNAME=	libasyncns
PORTVERSION=	0.7
CATEGORIES=	dns devel linux

MAINTAINER=	itetcu@FreeBSD.org
COMMENT=	C library for executing DNS queries asynchronously (Linux Fedora 10)

USES=		linux:f10
USE_LINUX_RPM=	yes
RPMVERSION=	1.fc10
USE_LDCONFIG=	yes

.include <bsd.port.mk>
