# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kitemmodels/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kitemmodels
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 models for Qt Model/View system

USE_QT5=	core dbus linguisttools widgets
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
