# $FreeBSD: branches/plasma5/QT/x11/qt5-x11extras/Makefile 10459 2014-11-03 10:46:24Z makc $

PORTNAME=	x11extras
DISTVERSION=	${QT5_VERSION}
CATEGORIES=	x11
PKGNAMEPREFIX=	qt5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Qt platform-specific features for X11-based systems

USE_QT5=	core gui widgets
QT_DIST=	x11extras
USES=		qmake
USE_LDCONFIG=	${PREFIX}/${QT_LIBDIR_REL}

.include <bsd.port.mk>
