# New ports collection makefile for:	trueos-meta-virtualboxguest
#
# $FreeBSD$
#

PORTNAME=	trueos-meta-virtualboxguest
PORTVERSION=	1373635705
CATEGORIES=	misc
MASTER_SITES=	# empty
DISTFILES=	# none

MAINTAINER=	kris@pcbsd.org
COMMENT=	The meta-port trueos-meta-virtualboxguest

RUN_DEPENDS=	virtualbox-ose-additions>=0:${PORTSDIR}/emulators/virtualbox-ose-additions

NO_BUILD=	yes

do-install:
	${DO_NADA}

.include <bsd.port.mk>
