# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kconfig/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kconfig
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 widgets for configuration dialogs

USE_QT5=	core gui linguisttools xml
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
