# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-fonts/plasma5-oxygen-fonts/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	oxygen-fonts
CATEGORIES=	x11-fonts kde # kde-plasma

COMMENT=	Plasma5 Oxygen font family

BUILD_DEPENDS=	fontforge:${PORTSDIR}/print/fontforge

USE_QT5=	core
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>

