# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-toolkits/kf5-kguiaddons/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kguiaddons
CATEGORIES=	x11-toolkits kde # kde-framework

COMMENT=	KF5 addons to QtGui

USE_QT5=	core gui widgets x11extras
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
