# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kidletime/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kidletime
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 library for monitoring user activity

USE_QT5=	core dbus gui widgets x11extras
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
