# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11/kf5-frameworks/Makefile 10851 2015-07-06 19:33:03Z tcberner $

PORTNAME=	frameworks
PORTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11 kde # kde-framework
PKGNAMEPREFIX?=	kf5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KF5 frameworks meta port

LICENSE=	LGPL20

USE_KDE5=	${_USE_KDE5_FRAMEWORKS_ALL}

USES=		metaport

.include <bsd.port.mk>
