# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11/kf5-kinit/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kinit
PORTREVISION=	1
CATEGORIES=	x11 kde # kde-framework

COMMENT=	KF5 process launcher to speed up launching KDE applications

USE_QT5=	core
USE_KDE5=	ecm kdeprefix kio service

OPTIONS_DEFINE=	DOCS NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
