# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-themes/kf5-kemoticons/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kemoticons
CATEGORIES=	x11-themes kde # kde-framework

COMMENT=	KF5 library to convert emoticons

USE_QT5=	core dbus gui widgets xml
USE_KDE5=	archive config coreaddons dbusaddons ecm i18n kdeprefix service

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
