# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/security/plasma5-ksshaskpass/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	ksshaskpass
CATEGORIES=	security kde # kde-framework

COMMENT=	Plasma5 ssh-add frontend

USE_QT5=	core
USE_KDE5=	coreaddons ecm i18n kdeprefix wallet widgetsaddons

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>
