# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/sysutils/plasma5-bluez-qt/Makefile 10824 2015-06-30 21:01:56Z tcberner $

# Note: this probably does not work yet (TOOD: find out if bluez-qt works on
#       on FreeBSD or what is needed to make it work).

PORTNAME=	bluez-qt
CATEGORIES=	sysutils kde # kde-plasma

COMMENT=	Qt wrapper for Bluez 5 DBus API

USE_QT5=	core dbus gui network qml widgets
USE_KDE5=	ecm

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>

