# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-themes/plasma5-breeze/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	breeze
CATEGORIES=	x11-themes kde # kde-plasma

COMMENT=	Plasma5 artwork, styles and assets for the Breeze visual style

USE_QT5=	core gui widgets xml
USE_KDE5=	config coreaddons decoration ecm frameworkintegration kcmutils kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>

