# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/plasma5-khotkeys/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	khotkeys
CATEGORIES=	devel kde # kde-plasma

COMMENT=	Plasma5 library for hotkeys

USE_QT5=	core dbus linguisttools
USE_KDE5=	ecm itemmodels kdeprefix plasma-framework plasma-workspace

OPTIONS_DEFINE=	DOCS NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>

