# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kdbusaddons/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kdbusaddons
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 addons to QtDBus

USE_QT5=	core dbus gui linguisttools x11extras
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
