# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/dns/kf5-kdnssd/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kdnssd
CATEGORIES=	dns kde # kde-framework

COMMENT=	KF5 abstraction to system DNSSD features

USE_QT5=	core dbus linguisttools network
USE_KDE5=	ecm kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
