# Created by: Dima Panov <fluffy@FreeBSD.org>
# $FreeBSD: ports/net/cagibi/Makefile,v 1.4 2012/06/06 06:44:11 miwi Exp $

PORTNAME=	cagibi
PORTVERSION=	0.2.0
CATEGORIES=	net devel
MASTER_SITES=	${MASTER_SITE_KDE}
MASTER_SITE_SUBDIR=	stable/cagibi

MAINTAINER=	kde@FreeBSD.org
COMMENT=	KDE SSDP/uPNP proxy

USES=		cmake tar:bzip2
USE_KDE4=	automoc4
USE_QT4=	corelib network xml dbus \
		qmake_build moc_build rcc_build uic_build

.include <bsd.port.mk>
