# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-threadweaver/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	threadweaver
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 addons to QtDBus

USE_QT5=	core network widgets xml
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
