# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/archivers/kf5-karchive/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	karchive
CATEGORIES=	archivers kde # kde-framework

COMMENT=	KF5 library that provides classes for handling archive formats

USE_QT5=	core
USE_KDE5=	ecm kdeprefix

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
