# $FreeBSD$

PORTNAME=	pywinrm
PORTVERSION=	0.2.2
DISTVERSIONPREFIX= v
CATEGORIES=	sysutils

MAINTAINER=	whatzgnu@gmail.com
COMMENT=	Python library for Windows Remote Management

LICENSE=	MIT

USES=		python
USE_PYTHON=	autoplist distutils

USE_GITHUB=	yes
GH_ACCOUNT=	diyan

.include <bsd.port.mk>
