# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/devel/kf5-kpty/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kpty
CATEGORIES=	devel kde # kde-framework

COMMENT=	KF5 pty abstraction

USE_QT5=	core
USE_KDE5=	coreaddons ecm i18n kdeprefix

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
