# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-themes/plasma5-plasma-workspace-wallpapers/Makefile 10824 2015-06-30 21:01:56Z tcberner $

PORTNAME=	plasma-workspace-wallpapers
CATEGORIES=	x11-themes kde # kde-framework

COMMENT=	Plasma5 wallpapers

USE_QT5=	core gui linguisttools uitools widgets
USE_KDE5=	ecm kdeclarative kdeprefix

.include "${.CURDIR}/../../x11/plasma5-plasma/bsd.plasma.mk"
.include <bsd.port.mk>
