# $FreeBSD: head/polish/calligra-l10n/Makefile 367888 2014-09-10 20:50:31Z gerald $

PORTNAME=	calligra-l10n
PORTVERSION=	${CALLIGRA_VERSION}
CATEGORIES=	polish editors kde

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Polish messages and documentation for Calligra

CALLIGRA_L10N=	pl

.include "${.CURDIR}/../../editors/calligra-l10n/files/bsd.l10n.mk"
.include <bsd.port.mk>
