# Created by: Tobias Berner <tcberner@gmail.com>
# $FreeBSD: branches/plasma5/KDE/x11-toolkits/kf5-kcompletion/Makefile 10823 2015-06-30 18:21:18Z tcberner $

PORTNAME=	kcompletion
CATEGORIES=	x11-toolkits kde # kde-framework

COMMENT=	KF5 text completion helpers and widgets

USE_QT5=	core gui linguisttools widgets xml
USE_KDE5=	config ecm kdeprefix widgetsaddons

OPTIONS_DEFINE=	NLS
OPTIONS_SUB=	YES

.include "${.CURDIR}/../../x11/kf5-frameworks/bsd.frameworks.mk"
.include <bsd.port.mk>
