#!/bin/sh

PREFIX=${PKG_PREFIX-/usr/local}

if [ "$2" != "POST-INSTALL" ] ; then
  exit 0
fi

# If this is during staging, we can skip for now
echo $PREFIX | grep -q '/stage/'
if [ $? -eq 0 ] ; then
  exit 0
fi

# Enable loading the nvidia binary driver
grep '^nvidia_load="YES"' /boot/loader.conf >/dev/null 2>/dev/null
if [ $? -ne 0 ] ; then
  echo 'nvidia_load="YES"' >>/boot/loader.conf
  echo 'nvidia-modeset_load="YES"' >>/boot/loader.conf
fi

exit 0
